#!/usr/bin/env bash

function custom_opts {
    if [ -f /etc/configurability/custom/java_opts ]; then
        source /etc/configurability/custom/java_opts
        export CUSTOM_OPTS=${CUSTOM_JAVA_OPTS}
    else
        memory_limits
    fi
}

function memory_limits {
    # If limits have not been passed to us then try to discover them
    if [ -z $MAX_HEAP_SIZE_XMX ]; then
        if [ -f /sys/fs/cgroup/memory/memory.limit_in_bytes ]; then
            MEMLIM=$(cat /sys/fs/cgroup/memory/memory.limit_in_bytes)
            MEMLIM=$(expr $MEMLIM / 1024 / 1024)
            [ $MEMLIM -lt 512 ] && MEMLIM=512
            [ $MEMLIM -gt 8192 ] && MEMLIM=8192
            export CUSTOM_OPTS="-Xmx${MEMLIM}m"
            echo "INFO: Setting default memory limit of $MAX_HEAP_SIZE_XMX"
        else
            export CUSTOM_OPTS="-Xmx512m"
            echo "WARNING: Setting default memory limit of 512m"
        fi
    fi
}

function tomcat_config {
    echo "Applying tomcat config"
    for envar in TC_MGR_GUI_USER \
                 TC_MGR_GUI_PASS \
                 TC_MGR_SCRIPT_USER \
                 TC_MGR_SCRIPT_PASS \
                 TC_MGR_JMX_USER \
                 TC_MGR_JMX_PASS \
                 TC_MGR_STATUS_USER \
                 TC_MGR_STATUS_PASS \
                 TC_ADMIN_GUI_USER \
                 TC_ADMIN_GUI_PASS \
                 TC_ADMIN_SCRIPT_USER \
                 TC_ADMIN_SCRIPT_PASS \
                 CUSTOM_OPTS
    do
        eval value=\$$envar
        find /opt/tomcat/ -type f -exec sed -i "s/<$envar>/$value/g" {} \;
    done

    cp -ruv /opt/tomcat/* /usr/share/tomcat

    [ -d /var/www/temp ] || mkdir -p /var/www/temp
    [ -d /var/www/conf ] || cp -r /usr/share/tomcat/conf /var/www/
    [ -d /var/www/webapps ] || cp -r /usr/share/tomcat/webapps /var/www/
}

function default_enable_8443 {
    perl -p0i -e 's/<!--(\n    <Connector port="8443".*\n.*\n.*\n.*\n.*\n.*\n.*\n)    -->/\1/' /usr/share/tomcat/conf/server.xml
}

default_enable_8443
custom_opts
tomcat_config
gen_keystore_jks
